[package]
name = "grafite"
description = "The Grafite Range Filter."
version = "0.1.1"
edition = "2021"
authors = ["Connor Tsui"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Connortsui20/grafite"
documentation = "https://docs.rs/grafite/latest/grafite/"
keywords = ["filter", "range", "bloom", "search", "succinct"]
categories = ["database-implementations", "data-structures", "algorithms"]

[dependencies]
miller_rabin = "1.1"
rand = "0.8"
vers-vecs = "1.4"
rayon = "1.10"
